#auto generated by gs package builder

### Below properties are hardcoded in fm template
# base directory of ant build
base.dir=./
# pacakage directory where packages needs to be stored
packages.dir=../packages/custom/gc
# temperory directory for zip and tar
temp.dir=./custom_temp/
# source directory of components

### Below properties are from config.yaml, they should had been built in package description already.
build.version=${yamlConfig["package"]["version"]}
build.package.name=${yamlConfig["package"]["name"]}
build.package.type=${yamlConfig["package"]["type"]}
custom.rule.jar=${yamlConfig["package"]["enginejar"]}
gs.version=${yamlConfig["package"]["baseversion"]}

#build.package.stream=gc
