#auto generated by gs package builder, should not be manually updated.

### Below properties are hardcoded in fm template.
### update the template, if you wan to change anything below.
# base directory of ant build
base.dir=./
# pacakage directory where packages needs to be stored
packages.dir=../packages/custom/gc
# temperory directory for zip and tar
temp.dir=./custom_temp/
# source directory of components

### Below properties are from config.yaml, they should had been built in package description already.
### update the config.yaml, if you wan to change anything below.
gs.version=${yamlConfig["target"]["gc"]["baseversion"]}
build.version=${yamlConfig["target"]["gc"]["buildversion"]}
build.package.name=${yamlConfig["target"]["gc"]["name"]}
build.package.type=${yamlConfig["target"]["gc"]["type"]}



#build.package.stream=gc
#====testing <mkdir dir="${(today)}!"$\{today}"}/>
