#auto generated by gs package builder, should not be manually updated.

### Below properties are hardcoded in fm template.
### update the template, if you wan to change anything below.
# base directory of ant build
base.dir=./
# pacakage directory where packages needs to be stored
packages.dir=../packages/custom/gc
# temperory directory for zip and tar
temp.dir=./custom_temp/
# source directory of components

### Below properties are from config.yaml, they should had been built in package description already.
### update the config.yaml, if you wan to change anything below.
gs.version=${yamlConfig["package"]["baseversion"]}
build.version=${yamlConfig["package"]["version"]}
build.package.name=${yamlConfig["package"]["name"]}
build.package.type=${yamlConfig["package"]["type"]}
build.engine.package.name=${yamlConfig["package"]["enginename"]}
build.engine.package.jar=${yamlConfig["package"]["enginejar"]}



#build.package.stream=gc
#====testing <mkdir dir="/${(today)!"$\{today}"}/>
