<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- generated by job scheduler generator, please do not manually update, contact psg if required -->
<job  title="${schedule.title}" stop_on_error="no">
    <settings >
        <mail_on_error ><![CDATA[no]]></mail_on_error>
        <mail_on_warning ><![CDATA[no]]></mail_on_warning>
        <mail_on_success ><![CDATA[no]]></mail_on_success>
    </settings>
    <params >
        <include  live_file="../Config/EmailParameters.xml"/>
        <param  name="task_name" value="${schedule.title}"/>
        <param  name="SLA" value="20"/>
        <param  name="file_name" value=""/>
        <param  name="pre_task_name" value="${schedule.dependency}"/>
        <param  name="pre_task_count" value="${schedule.dependencyCount}"/>
		<param  name="forceMailFlag" value="false"/>
		<param  name="taskCheckFlag" value="true"/>
        <param  name="hibernate_file" value="$SCHEDULER_DATA/config/reporting.hibernate.cfg.xml"/>
    </params>

    <script  language="shell">
        <![CDATA[
$GOLD_KSH/TriggerEvent.ksh ${schedule.title} PGGMPublishDailyReport PUB
        ]]>
    </script>
	
	<monitor.use  monitor="../Config/PreTaskCheck"/>
    <monitor.use  monitor="../Config/MailMonitor"/>
    <monitor.use  monitor="../Config/CheckJblgJobs"/>

	<run_time  time_zone="${schedule.timeZone}" single_start="${schedule.begin}">
        <weekdays >
            <day  day="${schedule.days}">
                <period  single_start="${schedule.begin}"/>
            </day>
        </weekdays>
    </run_time>
    
</job>