### important: key should not contain "."! e.g. "build.gc" will cause an exception

## to use the config in FreeMarker:
# ${yamlConfig["generator"]["typ"]}
## to use the config in Java:
# YamlConfig.getConfig("generator.typ");

generator:
   typ: local  ## tetsing
   componentpath:
      resource: /resources/
      vendordifinition: /vendordefinitions/
      workflow: /workflows/
      task: /tasks/
      ddl: /sql/DDL/
      dml: /sql/DML/
   file:
      packagedescriptiongc: 
         name: PackageDescription.xml
         template: PackageDescription.ftl
      packagedescriptionengine: 
         name: PackageDescription.Engine.xml
         template: PackageDescription.Engine.ftl
      buildxml:
         name: build.xml
         template: buildxml.ftl
      buildproperties:
         name: build.properties
         template: buildproperties.ftl
               
local:
   folder: D:\Projects\Nikko\E41-svn\trunk\customgc\configuration
#   folder: D:\Projects\Nikko\E41-svn\trunk\customdwh\configuration

svn:
   url: http://svn/psg/NIKKO/trunk/customgc/configuration
   user: dtao
   pass: Gsource@789
   versionfrom: 0
   versionto: 998
   
git:

package:
   baseversion: 8.7.2.10
   version: 8.7.2.01
   name: NIKKO_CustomGC
   type: full
   enginename: NIKKO_CustomEngine
   enginejar: NIKKOCustomRule.jar
#         stream: gc

ant:
   dir:
      base: ./
      temp: ./customgc_temp
      package: ./package

