### important: key should not contain "." !!!
### e.g. "buildgc" works fine, but "build.gc" causes an exception

### to use the config in FreeMarker:
# e.g. ${yamlConfig["generator"]["typ"]}
### to use the config in Java:
# e.g. YamlConfig.getConfig("generator.typ");

generator:
   typ: svn  ## one of local/svn/git
   componentpath:
      resource: /resources/
      vendordifinition: /vendordefinitions/
      workflow: /workflows/
      task: /tasks/
      ddl: /sql/DDL/
      dml: /sql/DML/
      plsql: /sql/PLSQL/
      gso: /gso/GSOConfig/
      saveLob: /reference/streetreffiles/
      saveDtd: /reference/rulexml/
      event: /events/
      engine: /engines/
      query: /queries/
      publishprofile: /publishingProfiles/
#   file:
#      packagedescriptiongc: 
#         name: PackageDescription.xml
#         template: PackageDescription.ftl
#      packagedescriptiondwh: 
#         name: PackageDescription.Dwh.xml
#         template: PackageDescription.Dwh.ftl
#      packagedescriptionengine: 
#         name: PackageDescription.Engine.xml
#         template: PackageDescription.Engine.ftl
#      buildxmlgc:
#         name: build.xml
#         template: buildxml.Gc.ftl
#         template: buildxml.ftl
#      buildxmldwh:
#         name: build.xml
#         template: buildxml.Dwh.ftl
#         template: buildxml.ftl
#      buildxmlengine:
#         name: build.xml
#         template: buildxml.Engine.ftl
      #buildproperties:
#         name: build.properties
#         template: buildproperties.ftl

target:  ## can be overwritten by runtime parameter -Dtarget=gc,engine
   gc:
      name: NIKKO_CustomGC
      baseversion: 8.7.2  
#      buildversion: 001   ## can be overwritten by runtime parameter -Dbuildversion=001
      type: Patch
      localfolder: D:\Projects\Nikko\E41-svn\trunk\customgc\configuration
      svnurl: http://192.168.224.182/psg/NIKKO/trunk/customgc/configuration
      svnversionfrom: 672
      giturl: https://github.com/dtdl/gspbuilder2.git # not available
      files:
         packagedescription:
            name: PackageDescription.xml
            template: PackageDescription.Gc.ftl
         buildxml:
            name: build.xml
            template: buildxml.ftl
   dwh: 
      name: NIKKO_CustomDWH
      baseversion: 8.7.2  
#      buildversion: 001   ## can be overwritten by runtime parameter -Dbuildversion=001
      type: full
      localfolder: D:\Projects\Nikko\E41-svn\trunk\customdwh\configuration
      svnurl: http://192.168.224.182/psg/NIKKO/trunk/customdwh/configuration
      svnversionfrom: 673
      files:
         packagedescription:
            name: PackageDescription.xml
            template: PackageDescription.Dwh.ftl
         buildxml:
            name: build.xml
            template: buildxml.ftl
#   engine: 
#      name: NIKKO_CustomEngine
#      enginejar: NIKKOCustomRule.jar
#      baseversion: 8.7.2  
#      buildversion: 001   ## can be overwritten by runtime parameter -Dbuildversion=001
#      type: full
#      localfolder: D:\Projects\Nikko\E41-svn\trunk\customjavarule\engines
#      svnurl: http://svn/psg/NIKKO/trunk/customjavarule/engines
#      packagedescription:
#         name: PackageDescription.Engine.xml
#         template: PackageDescription.Engine.ftl
#      buildxml:
#         name: build.Engine.xml
#         template: buildxml.Engine.ftl

# to be removed
local:
   folder: D:\Projects\Nikko\E41-svn\trunk\customgc\configuration
#   folder: D:\Projects\Nikko\E41-svn\trunk\customdwh\configuration

svn:
   user: dtao
   pass: Encrypted::9BD53DEF2BF0261457B2631229B58A17BCE1041138FC137B

   
git:
   user: dtao
   pass: Encrypted::9BD53DEF2BF02614312E837AE69EB66ACA15E231001F8766BCE1041138FC137B
   versionfrom: 0
   versionto: -1

   
#package:
#   baseversion: 8.7.2.x
#   version: 8.7.2.01
#   name: NIKKO_CustomGC
#   type: full
#   enginename: NIKKO_CustomEngine
#   enginejar: NIKKOCustomRule.jar
##         stream: gc

ant:
   dir:
      base: .
      configuration: ./configuration
      temp: ./custom_temp
      package: ../packages/custom/gc


#configExcel: ./input/pggm.csv.report.v1.xlsx
#targetFiles:
#   file1:
#      name: <title>.job.xml
#      template: pggm.csv.report.job.xml.ftl
#   file2:
#      name: <title>.properties
#      template: pggm.csv.report.properties.ftl
      
configExcel: ./input/pggm.pvc.v5.xlsx
targetFiles:
   file1:
      name: <title>.job.xml
      template: pggm.pvc.job.xml.ftl
   file2:
      name: <title>.properties
      template: pggm.pvc.properties.ftl