### important: key should not contain "." !!!
### e.g. "buildgc" works fine, but "build.gc" causes an exception

### to use the config in FreeMarker:
# e.g. ${yamlConfig["generator"]["typ"]}
### to use the config in Java:
# e.g. YamlConfig.getConfig("generator.typ");

generator:
   typ: local  ## one of local/svn/git
   componentpath:
      resource: /resources/
      vendordifinition: /vendordefinitions/
      workflow: /workflows/
      task: /tasks/
      ddl: /sql/DDL/
      dml: /sql/DML/
      plsql: /sql/PLSQL/
      gso: /gso/GSOConfig/
      saveLob: /reference/streetreffiles/
      saveDtd: /reference/rulexml/
      event: /events/
      engine: /engines/
      query: /queries/
   file:
      packagedescriptiongc: 
         name: PackageDescription.xml
         template: PackageDescription.ftl
      packagedescriptiondwh: 
         name: PackageDescription.Dwh.xml
         template: PackageDescription.Dwh.ftl
#      packagedescriptionengine: 
#         name: PackageDescription.Engine.xml
#         template: PackageDescription.Engine.ftl
      buildxmlgc:
         name: build.xml
#         template: buildxml.Gc.ftl
         template: buildxml.ftl
      buildxmldwh:
         name: build.xml
#         template: buildxml.Dwh.ftl
         template: buildxml.ftl
#      buildxmlengine:
#         name: build.xml
#         template: buildxml.Engine.ftl
      buildproperties:
         name: build.properties
         template: buildproperties.ftl

target:  ## can be overwritten by runtime parameter -Dtarget=gc,engine
   gc:
      name: NIKKO_CustomGC
      baseversion: 8.7.2  
      buildversion: 001   ## can be overwritten by runtime parameter -Dbuildversion=001
      type: full
      localfolder: D:\Projects\Nikko\E41-svn\trunk\customgc\configuration
      svnurl: http://svn/psg/NIKKO/trunk/customgc/configuration
      svnversionfrom: 634
      giturl: https://github.com/dtdl/gspbuilder2.git # not available
      files:
         packagedescription:
            name: PackageDescription.xml
            template: PackageDescription.Gc.ftl
         buildxml:
            name: build.xml
            template: buildxml.Gc.ftl
   dwh: 
      name: NIKKO_CustomDWH
      baseversion: 8.7.2  
#      buildversion: 001   ## can be overwritten by runtime parameter -Dbuildversion=001
      type: full
      localfolder: D:\Projects\Nikko\E41-svn\trunk\customdwh\configuration
      svnurl: http://svn/psg/NIKKO/trunk/customdwh/configuration
      svnversionfrom: 634
      packagedescription:
         name: PackageDescription.Dwh.xml
         template: PackageDescription.Dwh.ftl
      buildxml:
         name: build.Dwh.xml
         template: buildxml.Dwh.ftl
#   engine: 
#      name: NIKKO_CustomEngine
#      enginejar: NIKKOCustomRule.jar
#      baseversion: 8.7.2  
#      buildversion: 001   ## can be overwritten by runtime parameter -Dbuildversion=001
#      type: full
#      localfolder: D:\Projects\Nikko\E41-svn\trunk\customjavarule\engines
#      svnurl: http://svn/psg/NIKKO/trunk/customjavarule/engines
#      packagedescription:
#         name: PackageDescription.Engine.xml
#         template: PackageDescription.Engine.ftl
#      buildxml:
#         name: build.Engine.xml
#         template: buildxml.Engine.ftl

# to be removed
local:
   folder: D:\Projects\Nikko\E41-svn\trunk\customgc\configuration
#   folder: D:\Projects\Nikko\E41-svn\trunk\customdwh\configuration

svn:
   user: dtao
   pass: Encrypted::9BD53DEF2BF0261457B2631229B58A17BCE1041138FC137B

   
git:
   user: dtao
   pass: Encrypted::9BD53DEF2BF02614312E837AE69EB66ACA15E231001F8766BCE1041138FC137B
   versionfrom: 0
   versionto: -1

   
#package:
#   baseversion: 8.7.2.x
#   version: 8.7.2.01
#   name: NIKKO_CustomGC
#   type: full
#   enginename: NIKKO_CustomEngine
#   enginejar: NIKKOCustomRule.jar
##         stream: gc

ant:
   dir:
      base: ./
      temp: ./customgc_temp
      package: ./package

